# Generated by Django 4.0.2 on 2022-03-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='name',
            field=models.CharField(default='Название тарифа', max_length=256),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
