# Generated by Django 4.0.2 on 2022-03-08 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tariff_name_alter_tariff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название оператора', max_length=256)),
                ('website_link', models.CharField(default='/', max_length=256)),
                ('icon', models.ImageField(default='', upload_to='operator_icons/')),
            ],
        ),
        migrations.AddField(
            model_name='tariff',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.operator'),
        ),
    ]
