# Generated by Django 3.1.6 on 2022-03-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_operator_tariff_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='general_information',
            field=models.TextField(default='Общая информация о тарифе'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
