# Generated by Django 4.0.2 on 2022-03-14 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_operator_id_alter_tariff_id_supplementeduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementeduser',
            name='telephone_number',
            field=models.IntegerField(default=8),
        ),
        migrations.CreateModel(
            name='Favorite_fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.supplementeduser')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tariff')),
            ],
        ),
    ]
